language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kirylvolkau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kirylvolkau/docker-react npm run test